# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22810dce5a3b12929d3d27797148a0e2d7404905b0229779aa2109aeaefe292b4429aa5d6cd1141ec90df720680e1e62b9116a081950e7c089c9e7fa6423bd82

test:
  secret_key_base: a01b4add1f2120163212ae662b11ccf1e4e6a76fa26d733acc404edac868ca1beb90b45b08e59ebb733c1357fa0963cb988f07f48aedaa8e0041dd7bb86a7bfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
